### ISSUE TITLE
Queries are getting blocked while running using multithreading against default session pool

### ISSUE THREAD

**Issue by alkatrivedi** [googleapis/python-spanner#1024]
While running database queries using multiple threads, execution is getting blocked.
Reason: When a transaction is initialised, in case of Bursty Session Pool a new session will get created. While creating a session spanner_api method will get called to get the object reference to the spanner api. When there will be parallel execution of the queries using multiple threads, all the threads will try to create the spanner api object at the same time which is causing thread race in our program. This is why our execution is not Thread Safe and is getting blocked.

**Comment by alkatrivedi** [comment]
Code snippet(which is getting blocked while executing)
[multithreading.py.zip](https://github.com/googleapis/python-spanner/files/12927863/multithreading.py.zip)

**Comment by surbhigarg92** [comment]
@harshachinta Can you please triage this issue.

**Comment by bhatt4982** [comment]
Issue is not reproducible with the attached snippet...
@alkatrivedi also confirmed the same...

**Comment by harshachinta** [comment]
Not reproducible
