### ISSUE TITLE
Initialize a session for BurstyPool

### ISSUE THREAD

**Issue by larkee** [googleapis/python-spanner#108]
The default session pool BurstyPool does not create any sessions when bound and only creates them on demand. This means the first call made with this database will be slow. A session should be created when binding the pool to the database.

**Comment by skuruppu** [comment]
@larkee I think last time we discussed this issue, you said that implementing this support will over-complicate the pool implementation and may not be beneficial. If you explain the reasoning here, I think we can close this issue stating that we won't support this.

**Comment by larkee** [comment]
The issue with initializing the pool with a session is that a `BurstyPool` is created by default when creating a `Database` object. This includes for database that do not exist yet which causes a `NotFound` error. Additionally, when calling `list_databases` the returned `Database` protos are converted into `Database` objects. This means each `Database` returned would also create a session which could be problematic if there are large numbers of databases being listed. It also complicates a large percentage of existing tests.

Overall, implementing this support would over-complicate things for minimal benefit so we will not support this.
