### ISSUE TITLE
Database.__eq__ returns NotImplemented for comparison with other classes instead of raising the exception

### ISSUE THREAD

**Issue by odeke-em** [googleapis/python-spanner#1268]
I noticed this invalid code https://github.com/googleapis/python-spanner/blob/a6811afefa6739caa20203048635d94f9b85c4c8/google/cloud/spanner_v1/database.py#L445-L450

that it invokes `return NotImplemented` but __eq__ is supposed to return a boolean result of True or False and not an exception. I believe that the correct thing to do is raise that exception

Kindly /cc-ing @sakthivelmanii @harshachinta

**Comment by larkee** [comment]
From the Python docs:
https://docs.python.org/3.6/library/constants.html#NotImplemented

This appears to be the correct way of implementing comparison functions in Python.

**Comment by odeke-em** [comment]
Thank you @larkee for the education, I didn't know this!
