### ISSUE TITLE
spanner.Client().list_instances method filter_ parameter not working

### ISSUE THREAD

**Issue by Charles546** [googleapis/python-spanner#131]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-spanner/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: Alpine, MacOS,...
  - Python version: `3.8.2`
  - pip version: `20.1.1`
  - `google-cloud-spanner` version: `Version: 1.17.1`

#### Steps to reproduce

  1. Initialize a client
  2. Run `client.list_instances(filter_="name:something")`

#### Code example

```python
# example

from google.cloud import spanner

c = spanner.Client(project="my-project")
print([ i.instsance_id for i in c.list_instances(filter_="name:something") ])
print([ i.instsance_id for i in c.list_instances(filter_="labels.env:temp") ])

```

#### Stack trace
```
# example
```

The code doesn't throw exceptions or errors, but it gives the list of all instances ignoring the `filter_` parameter.

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by Charles546** [comment]
From the source shown here https://googleapis.dev/python/spanner/latest/_modules/google/cloud/spanner_v1/client.html#Client.list_instances

Looks like the `filter_` parameter is not used at all.

**Comment by c24t** [comment]
Looks like it was https://github.com/googleapis/python-spanner/commit/a23b1fff53b7d64f4481fe479c01b05bec19fd74 that broke this.

`InstanceAdminClient.list_instances` still takes this arg, the fix may be as easy as:

```diff
diff --git a/google/cloud/spanner_v1/client.py b/google/cloud/spanner_v1/client.py
index 0759fcf..fac2fe5 100644
--- a/google/cloud/spanner_v1/client.py
+++ b/google/cloud/spanner_v1/client.py
@@ -406,7 +406,7 @@ class Client(ClientWithProject):
         metadata = _metadata_with_prefix(self.project_name)
         path = "projects/%s" % (self.project,)
         page_iter = self.instance_admin_api.list_instances(
-            path, page_size=page_size, metadata=metadata
+            path, page_size=page_size, filter_=filter_, metadata=metadata
         )
         page_iter.item_to_value = self._item_to_instance
         page_iter.next_page_token = page_token
```

**Comment by wyardley** [comment]
Thanks @c24t 
also created support case #24587528 on the support side

**Comment by crwilcox** [comment]
That is an old commit! I believe we are going to be updating the generated portion of this library rather considerably in the near future, and can likely be sure this works in that release.

Is this blocking you or do you have a satisfactory workaround for the time?

**Comment by wyardley** [comment]
I'll defer to @Charles546 but don't think it's a blocker or time-sensitive
But might be good if a unit test could be added for this so that there isn't another regression?

**Comment by Charles546** [comment]
This is not a blocker for me, but it would be nice to have this fixed.  We use this API to monitor the existence and ages of some temp spanner instances, the filter will help us focus on the instance of interest and ignore the instance that suppose to be running.

**Comment by skuruppu** [comment]
CC @larkee who is currently working on the code migration.

**Comment by larkee** [comment]
I'm currently working on the migration but due to the amount of handwritten code, it's hard to say how long it will take. Given how simple the fix is, I'll write a PR and merge it for the release this week :+1:
