### ISSUE TITLE
Slow _merge_values ( parsing values from protobuf to string)

### ISSUE THREAD

**Issue by aguergolet** [googleapis/python-spanner#207]
https://github.com/googleapis/python-spanner/blob/4a58bcb4016977a8b2ae7fe886c4db40a13e85cd/google/cloud/spanner_v1/streamed.py#L103

We have a query returning 80.000 rows with 71 fields on the select list using Python3, Google Cloud Spanner API 1.17 (we tried 1.18, 1.19, and 2.x). I choose version 1.17 because the performance decreases with newer versions of API.

The query returns the data up to 0.9ms when I start to copy the rows from StreamedResultset iterator to a list.

I started to isolate the code, and I'm using an empty "for loop" to simulate the problem and discard any other application performance problem.

```
Code Snippet:

import threading
import time
import os
from google.cloud.spanner import Client, PingingPool
from google.cloud.spanner_v1 import instance, database

"""Queries sample data from the database using SQL."""

projectId = 'cerc2-datalake-int-01'
instanceId = 'datalake-int-spanner-01'
database_id = 'cerc_datalake_bk_int14'

spanner_client = Client(projectId)

instance = spanner_client.instance(instanceId)
database = instance.database(database_id)

# Read query from query.sql file.
file = open('query.sql',mode='r')
content  = file.read()
file.close()

# Executing the query
start = time.time()
print('Starting query')
with database.snapshot() as snapshot:
    results = snapshot.execute_sql(
        content 
    )
end = time.time()
print(f'Query execution time: {end - start}')

# Count returned rows ( USING VERSION 2.x:  Error in this piece of code, some timestamp conversion error into google-core-api - removed all datetime fields to test)
start = time.time()
i = 0    
for row in results:
    i+=1
end = time.time()
print(f'Iterate itens {end - start}')


```
Using cProfile libraries to profile the application, I realized that the call of method _parse_value_pb inside _merge_values into streamed.py is the slowest method in my application. 

For testing purposes, I removed the streamed.py file line 106:
>> self._current_row.append(_parse_value_pb(value, field.type))

The line has been replaced by: 
>> self._current_row.append(value, field.type)

The first scenario (with _parse_value_pb):
Query 0.9ms, resultset iteration: 25 seconds;

The second scenario, removing _parse_value_pb:
Query 0.9ms, resultset iteration: 6 seconds;

All these tests is running on my 2.4Ghz laptop, but when we use Appengine, this routine gets more than 120 seconds;

I've tested with google spanner library 2.1 version, I got 103 seconds instead of 25 seconds ( version 1.17), with the same behavior;

The performance is fair when the resultset has many rows and a few columns in each row. I tested up to 30 resultset columns, and this behavior is not a problem. In my case, I need to work with 71 columns in each row.

**Comment by larkee** [comment]
Hi André,

I was able to reproduce this issue by creating a table with 71 string columns and 95000 rows and calling `SELECT * from ColumnsTest`. Using v1.17.0 I was able to get the following times:

The first scenario (with _parse_value_pb):
```
ResultSet Iteration: 22.080 seconds;
```

The second scenario, removing _parse_value_pb:
```
ResultSet Iteration: 14.002 seconds;
```

These times don't match yours exactly which I suspect is to due to different column types and data.

Using a profiler, I was able to identify some minor optimizations which gives the following timing:
```
ResultSet Iteration: 18.196 seconds;
```

I've pushed these changes to [this branch](https://github.com/larkee/python-spanner/tree/1.17.0-streamed-optimisation) if you'd like to try them. 

I am aware that v2.x has significantly reduced performance due to a new dependency on the `proto-plus` library. I need to take some time to do some benchmarking and optimizing but unfortunately I haven't had the cycles to do so recently.

I will need more time to look into possible further optimizations for this v1.17.0 branch but I hope that the changes I've provide help in the meantime :+1:

**Comment by larkee** [comment]
I have managed to make some further optimizations which give the following timing:
```
ResultSet Iteration: 12.071s
```
As a note, all of these timings have been using the cProfiler in IntelliJ. If I run the script directly from the command line with these optimizations, I get 5.742s.

These additional optimizations have been pushed to the aforementioned branch. The command to install it is:
```
pip install git+https://github.com/larkee/python-spanner.git@1.17.0-streamed-optimisation
```

**Comment by aguergolet** [comment]
Thanks for the reply, I tested the version proposed. 

My machine ran the code using 1.17 official version in 21 seconds vs 10 seconds using your  optimized version.

The query running on web client ou spanner-cli: 0.532ms

It's a good improvement, we are considering to migrate to Java ( 4 seconds ) but we a lot of work to do. 

This new library is a good workaround for while, but we changed some fileds to NUMERIC, and the 1.17 doesn't support numeric Data Type. Is it possible to apply these adjustments on 1.19.1 too?

Error using Numeric Fields:
```
Starting query
Query execution time: 0.5202188491821289
Traceback (most recent call last):
  File "app.py", line 43, in <module>
    for row in results:
  File "/home/andre.guergolet/.local/lib/python3.8/site-packages/google/cloud/spanner_v1/streamed.py", line 146, in __iter__
    self._consume_next()
  File "/home/andre.guergolet/.local/lib/python3.8/site-packages/google/cloud/spanner_v1/streamed.py", line 138, in _consume_next
    self._merge_values(values)
  File "/home/andre.guergolet/.local/lib/python3.8/site-packages/google/cloud/spanner_v1/streamed.py", line 106, in _merge_values
    self._current_row.append(_parse_value_pb(value, field_types[index]))
  File "/home/andre.guergolet/.local/lib/python3.8/site-packages/google/cloud/spanner_v1/_helpers.py", line 206, in _parse_value_pb
    raise ValueError("Unknown type: %s" % (field_type,))
ValueError: Unknown type: code: 10
```


I changed the streamed.py to print more details of this error:

I think that is a newly recently created NUMERIC fields,

**Comment by larkee** [comment]
Thanks for the update. I'm glad 

I've applied the changes to 1.19.1 and they can be installed with the following command:
```
pip install git+https://github.com/larkee/python-spanner.git@1.19.1-streamed-optimisation
```

I'm also looking into a possible workaround for v2.1.0 which should reverse the performance loss you noted and fix the datetime bug. However, I need to more time to test it properly. I'll keep posting updates here :+1:

**Comment by larkee** [comment]
Unfortunately I have not had time in the past week to work on the performance loss workaround for the most recent version.

@aguergolet Is the 1.19.1 branch working? Would you prefer to use the most recent version of the library after the fixes? Please let me know so I can reprioritize this issue as needed :+1:

**Comment by aguergolet** [comment]
This version worked. But we rewrite all of our applications using Java, performance is a big issue to us.

If you need new tests using the python library, I could test to contribute.
