### ISSUE TITLE
run_in_transaction doesn't throw errors unless I explicitly query the result

### ISSUE THREAD

**Issue by tellmeaboutcode** [googleapis/python-spanner#243]
I have numerous SQL files that I am trying to run under one transaction. I will not have any visibility into the type (DDL/DML) of the SQL statements. I am trying to use `execute_sql` and `run_in_transaction` and want to show the file name and the error message in case any of those files contain bad SQL. I realized the `run_in_transaction` doesn't report/throw errors unless I explicitly try to access the result of each query.

Can `run_in_transaction` throw errors when `execute_sql` fails?

Example:
```
spanner_client = spanner.Client()
instance = spanner_client.instance("testInst")
database = instance.database("testdb")
def execute_transaction(transaction):
    query = "SELECT SingerId, AlbumId, AlbumTitle FROM NonExistentTable"
    transaction.execute_sql(sql=query)
try:
   result = database.run_in_transaction(execute_transaction)
except GoogleAPICallError as e:
   print(e)
```

**Comment by larkee** [comment]
Hi there,

This behaviour is because `transaction.execute_sql` returns a generator which means the requests to the backend are not made until the results are iterated over. This is because the method is intended for read requests where you will be iterating over the results.

For write requests i.e. DML/DDL, `transaction.execute_update` can be used. This will execute the query immediately and return a count of the rows affected. I think this method will suit your use case if you do not need to iterate over the results. I can confirm it works for your example:

Code:
```
spanner_client = spanner.Client()
instance = spanner_client.instance("testInst")
database = instance.database("testdb")
def execute_transaction(transaction):
    query = "SELECT SingerId, AlbumId, AlbumTitle FROM NonExistentTable"
    transaction.execute_update(query)
try:
   result = database.run_in_transaction(execute_transaction)
except GoogleAPICallError as e:
   print(e)
```

Output:
```
400 Table not found: NonExistentTable [at 1:43]\nSELECT SingerId, AlbumId, AlbumTitle FROM NonExistentTable\n
```

I hope this helps. Let me know if you run into any more issues :+1:

**Comment by tellmeaboutcode** [comment]
@larkee Thank you that was helpful. However, I am having issues running a DDL statement.

Code example:
```
spanner_client = spanner.Client()
instance = spanner_client.instance("testInst")
database = instance.database("testdb")
def execute_transaction(transaction):
    query = """CREATE TABLE Singers (
SingerId     INT64 NOT NULL,
FirstName    STRING(1024),
LastName     STRING(1024),
SingerInfo   BYTES(MAX)
) PRIMARY KEY (SingerId)"""
    transaction.execute_update(query)
try:
   result = database.run_in_transaction(execute_transaction)
except GoogleAPICallError as e:
   print(e)
```
Output: 
```
400 Statement not supported: CreateTableStmt [at 1:1]
CREATE TABLE Singers (
^
```

My use case here is that I will have a mix of DDL and DML statements that I won't have visibility into. My code will just run those statements in a transaction and report errors if any. 

Could you please provide suggestions on how to achieve this?

**Comment by larkee** [comment]
Ah, I see. Cloud Spanner does not support DDL statements in transactions. DDL statements must be executed via `database.update_ddl()`.

I don't know your exact use case but I see two options:
1) Classify the statements into DDL and DML and then execute those together, e.g.
```
# NOTE: This is a basic implementation for the sake of an example.
# It may not handle edge cases.
def is_ddl(statement):
    if statement.split()[0].upper() in ["CREATE", "DROP", "RENAME", "ALTER"]:
        return True
    return False
 

def execute_transaction(transaction, statements):
    for statement in statements:
        transaction.execute_update(statement)


spanner_client = spanner.Client()
instance = spanner_client.instance("testInst")
database = instance.database("testdb")

# Classify statements.
ddl_statements = []
dml_statements = []
for statement in statements:
    if is_ddl(statement):
        ddl_statements.append(statement)
    else:
        dml_statements.append(statement)

# Handle DDL statments.
operation = database.update_ddl(ddl_statements)
operation.result()

# Handle DML statements.
try:
   result = database.run_in_transaction(execute_transaction, dml_statements)
except GoogleAPICallError as e:
   print(e)
```
This will keep the DDL statements together in one request and the DML statements together in one transaction. However the DDL statements will all be run before the DML statements.

2) Run each statement individually e.g.
```
# NOTE: This is a basic implementation for the sake of an example.
# It may not handle edge cases.
def is_ddl(statement):
    if statement.split()[0].upper() in ["CREATE", "DROP", "RENAME", "ALTER"]:
        return True
    return False
    
   
def execute_transaction(transaction, statement):
    transaction.execute_update(statement)


spanner_client = spanner.Client()
instance = spanner_client.instance("testInst")
database = instance.database("testdb")

for statement in statements:
    try:
        if is_ddl(statement):
            operation = database.update_ddl([statement])
            operation.result()
        else:
            result = database.run_in_transaction(execute_transaction, statement)
    except GoogleAPICallError as e:
       print(e)
```
This will maintain the order of the DDL and DML statements but each statement will be executed individually.


I hope these suggestions are helpful. Once again, let me know if you have further questions :+1:

**Comment by tellmeaboutcode** [comment]
@larkee Thanks a lot. So much useful information. My use case is to support spanner for database schema migrations. The way it works is that users will be able to create a bunch of SQL files (DDL/DML statements) with a specific naming convention (eg. timestamps) that is needed to track the order of migrations. My tool will take care of applying these SQL changes in that specific order and log these timestamps to a tracking table.

Option 1 doesn't work for my use case as it will mess up the order in which the changes are getting applied.

Option 2 will maintain the order but if the last migration fails, the state will get messed up because rollback is not happening. :(

**Comment by tellmeaboutcode** [comment]
@larkee Feel free to close this out as the feature is not supported by cloud spanner.
