### ISSUE TITLE
spanner: fix Database.session vs SessionCheckout context manager

### ISSUE THREAD

**Issue by odeke-em** [googleapis/python-spanner#25]
This is an experience report coming from a use case for which this API client had never been considered for. I am working on the spanner-django ORM plugin. My use case requires me to hold a Transaction alive for a few seconds as it is used in various functions for a while.

### Problem statement

The design of this API client assumes that folks with all invoke database.run_in_transaction to run a bunch of code within one function, and database.run_in_transaction will handle retries, context checkouts and the session that'll create the Transaction.

In https://github.com/googleapis/python-spanner/issues/10#issuecomment-585056760, @larkee pointed out to me that my usage of spanner_v1.Database.session() doesn't create a session from the pool that I might have provided! That came as a huge surprise to me and could explain a bunch of random errors I was getting from Spanner's server with `NOT FOUND Session`.

To even make this work, I had to fumble and read through the implementation details and access private methods i.e.
```python
global_session_pool = spanner.pool.BurstyPool()

def connect(...):
    # Correctly retrieve a session from the global session pool.
    # See:
    #   * https://github.com/orijtech/django-spanner/issues/291
    #   * https://github.com/googleapis/python-spanner/issues/10#issuecomment-585056760
    #
    # Adapted from:
    #   https://bit.ly/3c8MK6p: python-spanner, Git hash 997a03477b07ec39c7184
    #   google/cloud/spanner_v1/pool.py#L514-L535
    # TODO: File a bug to googleapis/python-spanner asking for a convenience
    # method since invoke database.session() gives the wrong result
    # yet requires a context manager wrapped with SessionCheckout
    # and needs accessing private methods, which leaks the details of the
    # implementation in order to try to use it correctly.
    pool = db._pool
    session_checkout = spanner.pool.SessionCheckout(pool)
    session = session_checkout.__enter__()
    if not session.exists():
        session.create()
    return_session = lambda: session_checkout.__exit__() # noqa

    return Connection(db, session, return_session)
```

### Suggestion
The presence of spanner_v1.Database.session() as a public method that totally by-passes the use of the pool that the user passed in basically, is a surprise and easily creates misuse that's very subtle to miss.

I think we can make this a whole lot easier to use without misuse by perhaps
```python
session = database.checkout_session()
...
database.return_session(session)
```

where `checkout_session()` will handle the logic of the SessionCheckout

and then finally deprecate `spanner_v1.Database.session()` which oddly requires the caller to then check if the session exists first and at the end also invoke session.delete()

The suggestion above will remove all that cognitive load.

Thank you!

**Comment by larkee** [comment]
Thanks for filing this issue and apologies for the delayed response!

Unfortunately, we will not be adding this feature. The best practices are [to hide session details from the client library user](https://cloud.google.com/spanner/docs/sessions#hide_session_details_from_the_client_library_user) to avoid session management by the user. This is to minimize the risk of session leakage. 

The suggestion above introduces a high risk of session leakage if a user forgets to return the session after use. 

We apologize for the inconvenience this causes.
