### ISSUE TITLE
overly strict dependency on proto-plus

### ISSUE THREAD

**Issue by tswast** [googleapis/python-spanner#279]
We noticed in building an internal tool that the Spanner dependency is much more strict than in other packages, such as BigQuery.

https://github.com/googleapis/python-spanner/blob/1b0ce1d2986085ce4033cf773eb6c5d3b904473c/setup.py#L36

Since `proto-plus` is a core dependency of all client libraries, it is often bundled with an environment (e.g. in AI Platform Notebooks). The strict dependency makes it much harder to upgrade the `google-cloud-spanner` library in these environments.

**Comment by larkee** [comment]
The strictness of the dependency came from and issue during the migration to v2.0 when I needed to pin to v1.10-dev2. It seems when I upgraded to 1.11.0 I kept the `==` rather than using `>=`. I've written a PR to update the dependency :+1:
