### ISSUE TITLE
Incorrect issue links in CHANGELOG.md in last release notes

### ISSUE THREAD

**Issue by IlyaFaer** [googleapis/python-spanner#28]
By chance I've caught my eye on broken issue URLs in CHANGELOG.md (only in 1.14.0 release). For example:
![image](https://user-images.githubusercontent.com/26030071/75869292-6c752a80-5e1a-11ea-8cac-9c12e5c33d83.png)

This one leads to **python-spanner**/issues/10183, but in fact original issue is **google-cloud-python**/pull/10183

@larkee, PTAL. It's not a problem to fix couple of links, but I assume it was done by release tool or some kind of a script, so it can repeat in future

**Comment by IlyaFaer** [comment]
@frankyn, @pradn, I see the same problem in [Storage](https://github.com/googleapis/python-storage/blob/master/CHANGELOG.md#features) (see "#9889") and [PubSub](https://github.com/googleapis/python-pubsub/blob/master/CHANGELOG.md#120-2020-02-05)

**Comment by pradn** [comment]
I've pushed a PR for the issue in PubSub. We're going to keep seeing this as we fix old bugs. We just need to be vigilant, I guess. I don't see an easy way to fix it.

**Comment by larkee** [comment]
There are no spanner issues or PRs in the old repo so we shouldn't encounter this problem anymore. If it comes up again, feel free to reopen this issue.
