### ISSUE TITLE
Transaction's execute_update default timeout

### ISSUE THREAD

**Issue by tellmeaboutcode** [googleapis/python-spanner#312]
Hello

I tried looking into the documentation but I couldn't find out what's the default timeout that is set for `transaction.execute_update`.  May I know what's the default timeout that is set?

I have a giant insert statement with ~9000 rows that's failing with the error: 504 Deadline Exceeded. Is there a limit on the number of rows that I can insert or can I just increase the timeout?

```
INSERT INTO tests (value1,value2,value3,value4,value5,value6,value7,value8,value9,value10,value11,value12,value13,value14) VALUES 
('a9a','GB','0101200',59,0.0,0.0,999,999,0,'null','null','null','null','10-04-2025') ... 9000
```

**Comment by larkee** [comment]
Hi there,

The documentation for Spanner client timeouts can be found [here](https://cloud.google.com/spanner/docs/custom-timeout-and-retry). Currently, there are not samples for Python as we only recently added the support. But to answer your question, `execute_update` uses the `execute_sql` method which has a [timeout of `30s`](https://github.com/googleapis/googleapis/blob/master/google/spanner/v1/spanner_grpc_service_config.json#L97). 

However, from your use case description, I would recommend using the [mutations API](https://cloud.google.com/spanner/docs/modify-mutation-api) over using DML statements. It will batch the changes together to be sent as a commit call which has a [timeout of `1hr`](https://github.com/googleapis/googleapis/blob/master/google/spanner/v1/spanner_grpc_service_config.json#L27). While there is a limit of 20k mutations per commit, there is also a significant performance improvement associated with using mutations. More information about mutations vs DML can be found [here](https://cloud.google.com/spanner/docs/dml-versus-mutations).

Let me know if you have any further questions about this :+1:

**Comment by larkee** [comment]
I'm going to close this issue since it has been a week with no response. If you feel I haven't answered your question, please feel free to reopen.
