### ISSUE TITLE
Retry Transaction Outcome Unknown errors

### ISSUE THREAD

**Issue by olavloite** [googleapis/python-spanner#335]
Cloud Spanner can return the error `Transaction Outcome Unknown` if a transaction fails with an unknown transient reason. It is safe to retry the entire transaction when this error is returned, even though the error message indicates that the outcome is inconclusive. The specific error should therefore be added to the conditions for retrying a transaction.

I don't know exactly which errors are automatically retried for transactions in the Python client. It could be that this specific error condition already has been added to the list of errors to retry, but in most of the other client libraries currently only `Aborted` is retried.

cc @skuruppu

**Comment by larkee** [comment]
@olavloite Do you know what status code this would be?

Python uses exception types that are mapped from status codes as defined [here](https://github.com/googleapis/python-api-core/blob/master/google/api_core/exceptions.py). Depending on the error type, we may need to add logic to retry for that specific error message.

**Comment by olavloite** [comment]
> @olavloite Do you know what status code this would be?
> 

It is status code `UNKNOWN` (2).

**Comment by skuruppu** [comment]
Closing this issue as we have decided to not proceed with this for now.
