### ISSUE TITLE
Best way to run multiple DML statements at once

### ISSUE THREAD

**Issue by tellmeaboutcode** [googleapis/python-spanner#338]
Hello

I have multiple DML statements with a mix of a few inserts, updates, and delete statements. Currently, I am using the transaction's `execute_update` to run each DML statement but doesn't work with running them all at once. 

Are there any suggestions on how can I run multiple DML statements at once assuming that I do not know what type of DML statements they are?

**Comment by larkee** [comment]
Hi there,

It sounds like you want to use the `Transaction.batch_update()` method. It takes in a list of DML statements and executes them in order. It should execute much faster as all the statements are sent together. The difference between `execute_update` and `batch_update` usage is shown below:

```
def use_batch_update(transaction, dml_statements):
    transaction.batch_update(dml_statements)


def use_execute_update(transaction, dml_statements):
    for dml in dml_statements:
        transaction.execute_update(dml)


# Run each statement separately.
database.run_in_transaction(use_execute_update, statements)

# Run all statements together.
database.run_in_transaction(use_batch_update, statements)
```

Let me know if you have any further questions about this :+1:
