### ISSUE TITLE
Investigate and compare performance of single-thread, multi-thread, and multi-process approaches

### ISSUE THREAD

**Issue by larkee** [googleapis/python-spanner#346]
In #332, @hadim mentioned that the multi-threading example had equivalent performance to single-threading. It would be nice to investigate this and confirm whether this is consistently true due to the GIL, or if it is just for this example.

Additionally, it would be nice to look into multi-processing further and provide examples for different use cases. If the multi-threading example *is* equivalent to single-threading, it may be worth updating the example to use multi-processing instead to match the intent.

**Comment by asthamohta** [comment]
This project has been pursued by our intern and we have benchmarked these numbers.
