### ISSUE TITLE
Samples tests are leaking resources in the test project

### ISSUE THREAD

**Issue by leahecole** [googleapis/python-spanner#382]
Hey! @ivanmkc noticed that spanner has a lot of extra resources in the test project and from what I can tell, they are likely created from one of these tests. We need to ensure that the delete call happens regardless of test outcome. Please feel free to reach out to me or anyone in @googleapis/python-samples-owners if you need help with this, or to join us at office hours (Ping me for calendar invite)

https://github.com/googleapis/python-spanner/blob/master/samples/samples/autocommit_test.py
https://github.com/googleapis/python-spanner/blob/master/samples/samples/backup_sample_test.py
https://github.com/googleapis/python-spanner/blob/master/samples/samples/snippets_test.py
![Screen Shot 2021-06-23 at 4 39 45 PM](https://user-images.githubusercontent.com/6719667/123165665-5f25ea00-d429-11eb-8224-3e6e1df2bdda.png)

**Comment by ivanmkc** [comment]
Thanks @leahecole. I should note that most of the instances are empty or near empty.
