### ISSUE TITLE
Remove 'test_utils' fossil

### ISSUE THREAD

**Issue by tseaver** [googleapis/python-spanner#400]
Unused: https://github.com/googleapis/python-spanner/tree/master/test_utils

**Comment by dseomn** [comment]
Isn't this still used here? https://github.com/googleapis/python-spanner/blob/b79c9957eb101ed2afcfc7565bb08e79499a28f3/tests/system/_helpers.py#L22-L23

**Comment by dseomn** [comment]
Oh I see, that's using https://github.com/googleapis/python-test-utils now, right?

**Comment by tseaver** [comment]
@dseomn Yup, that is correct.
