### ISSUE TITLE
KeyError with type_.code 10 when querying large set

### ISSUE THREAD

**Issue by YukiSou** [googleapis/python-spanner#433]
![image](https://user-images.githubusercontent.com/4012069/127454734-747530af-7ee1-41c0-a2ae-e3c60120afe9.png)
Success when query with limitation, but failed without it.

**Comment by larkee** [comment]
Thank you for your detailed error!

I've tracked down the issue and written the fix. It will be include the next release which should be within the next 24 hours :+1:
