### ISSUE TITLE
Test code samples under CI

### ISSUE THREAD

**Issue by larkee** [googleapis/python-spanner#5]
The documentation hosted on googleapis.dev is out of date and the code examples throw errors. These are contained here and need to be updated.

**Comment by larkee** [comment]
Looked into this a couple weeks ago and have an idea of how to proceed. Will work on this next time I get some downtime.

**Comment by harshachinta** [comment]
@larkee 
Can you please give some context and additional information on this issue?
AFAIK, all code samples in https://cloud.google.com/spanner/docs/getting-started/python and https://github.com/googleapis/python-spanner/tree/main/samples/samples are validated through a presubmit `Samples - Python` and should not be out of date.
