### ISSUE TITLE
Use inclusive words and update pylint.config

### ISSUE THREAD

**Issue by dandhlee** [googleapis/python-spanner#548]
There are mentions of non-inclusive words in pylint.config. Not sure how to update this file, please update it from `master` to `main` or other applicable inclusive terms. Please also update any other mentions of non-inclusive terms in the library proto or in this repository in general!

**Comment by larkee** [comment]
The non-inclusive words in pylint.config are a result of the imported pylint code. The change would first need to be made in that repo: https://github.com/GoogleCloudPlatform/python-repo-tools

**Comment by dandhlee** [comment]
Thanks for pointing where it comes from! Never seen it for myself until now 😅 

Origin: https://github.com/GoogleCloudPlatform/python-repo-tools/blob/master/gcp_devrel/tools/pylint.py

**Comment by tseaver** [comment]
@larkee, @dandhlee We no longer actually use `pylint` at all (since https://github.com/googleapis/google-cloud-python/pull/4921). Fossils removed in PR #561.
