### ISSUE TITLE
cursor.list_tables() is returning views as well

### ISSUE THREAD

**Issue by vi3k6i5** [googleapis/python-spanner#591]
cursor.list_tables() is returning views as well

#### Environment details

  - OS type and version: Mac, latest
  - Python version: `python --version` 3.9
  - google-cloud-spanner              3.10.0

#### Steps to reproduce

  1. Create a view
  2. cursor.list_tables() # will return the view as well.

Thanks!

**Comment by vi3k6i5** [comment]
@larkee : what would be the right way to fix this, should we add a parameter in this method 

```
cursor.list_tables(include_views=<boolean>)
```

based on the value of `include_views` it will include views?

Another approach would be to not modify the method signature and update the query to return only tables.
Create a separate method to list views?

```
cursor.list_tables() # returns list of tables. <backend Sql will be updated for this>
cursor.list_views() # returns list of views.
```

Any other suggestion is welcome.

**Comment by rajatbhatta** [comment]
Spanner treats both tables and views as tables, and the nomenclature is BASE TABLE for standard tables, and VIEW for views. ([Reference](https://cloud.google.com/spanner/docs/information-schema#:~:text=TABLE_TYPE,the%20value%20VIEW))

IMO, we can consider going with the first approach and have the include_views <boolean> as True by default (to match the spanner nomenclature as mentioned above).
We can have separate SQL statements being executed based on the flag.

// Includes both base tables and views (include_views is true - default)
```
SQL_LIST_TABLES = """
SELECT table_name
FROM information_schema.tables
WHERE table_catalog = '' AND table_schema = ''
"""
```

// Includes only base tables (include_views is false)
```
SQL_LIST_BASE_TABLES = """
SELECT table_name
FROM information_schema.tables
WHERE table_catalog = '' AND table_schema = '' AND table_type = 'BASE TABLE'
"""
```

**Comment by asthamohta** [comment]
I agree with Rajat
Suddenly creating two functions as you suggested might be a breaking change for people who might be using this fxn already and want views. Rather we can set default value to true and then if people want they can set it to false.
