### ISSUE TITLE
update readme 

### ISSUE THREAD

**Issue by anukaal** [googleapis/python-spanner#645]
add python version 3.9 and 3.10 in the README.rst section

**Comment by IlyaFaer** [comment]
@anukaal, as far as I understand, you're talking about this section:

----------------------------------------------------
![Безымянный](https://user-images.githubusercontent.com/26030071/143406216-d0abc83f-9b04-4a24-87c2-691675e96c21.png)

----------------------------------------------------
Looking at the code, I expect the next `python-spanner` release on PyPl to make it right. There is already a commit which adds classifiers for Python 3.9 and 3.10: https://github.com/googleapis/python-spanner/pull/626

This commit was simply done after the last release, so the classifiers are not yet there.

**Comment by skuruppu** [comment]
It's fixed now.
