### ISSUE TITLE
Regenerate the client for the new CreateBackup timeout

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/python-spanner#68]
Currently the default timeout for `CreateBackup` seems to be [30 seconds](https://github.com/googleapis/python-spanner/blob/1d4976634cb81dd11b0ddc4bfc9fe9c61a7e7041/google/cloud/spanner_admin_database_v1/gapic/database_admin_client_config.py#L60).

It seems like the new configuration is 1 hour ([spanner_admin_database_gapic.legacy.yaml](https://github.com/googleapis/googleapis/blob/5dca7f1079a4c127245c0f1dbb8293b434fbd0c8/google/spanner/admin/database/v1/spanner_admin_database_gapic.legacy.yaml#L194), [spanner_admin_database_gapic.yaml](https://github.com/googleapis/googleapis/blob/5dca7f1079a4c127245c0f1dbb8293b434fbd0c8/google/spanner/admin/database/v1/spanner_admin_database_gapic.yaml#L70)).

**Comment by larkee** [comment]
Backup timeout configs have been regenerated and [merged](https://github.com/googleapis/python-spanner/pull/65). It will be included in the next release.
