### ISSUE TITLE
Backup tests are flaky

### ISSUE THREAD

**Issue by larkee** [googleapis/python-spanner#83]
The Kokoro tests are often failing on backup tests for unrelated changes. There are two problems:
- `UpdateBackup` sometimes times out with DEADLINE_EXCEEDED as seen in https://github.com/GoogleCloudPlatform/python-docs-samples/issues/3241
- `test_list_backups` is failing due to a backup from a different test being included in the returned list for `size_bytes`

The first problem can be resolved by increasing the timeout for `UpdateBackup`.

The second problem is difficult to replicate and the exact cause is unclear given that the tests are not run in parallel and the backups are being deleted at the end of each test. The simplest solution will be to modify the test to ensure that no backups from previous tests meet the condition.

**Comment by tmatsuo** [comment]
The test job can be killed anytime, so potentially we may have leaked backups (or any other resources).
