### ISSUE TITLE
Memory leak in google-cloud-spanner when performing a simple query (noticeable when retrieving a lot of data) 

### ISSUE THREAD

**Issue by javilasparta** [googleapis/python-spanner#860]
#### Environment details

  - OS type and version: ANY (However executed the provided sample in macOS Monterey Version 12.3.1)
  - Python version: Python 3.9.7
  - pip version: pip 22.3.1
  - google-cloud-spanner version: 3.24.0

#### Steps to reproduce

  1. Create a sample table with 10 STRING columns (the more columns with data the worst it gets)
  2. Add at least 1000.000 records to it (add data to all columns).
  3. Query the created table multiple times when running the application/script, with a limit of 250.000
  4. Observe memory is not released after the first execution, instead it increases a lot after the first one, then it keeps increasing a little bit on each iteration without releasing memory.

#### Code example (To query the data)

```python

import psutil # to print current memory after each iteration
from google.cloud import spanner

def _query_data(database):
    """Queries sample data from the database using SQL."""

    iteration_counter = 0
    with database.snapshot() as snapshot:
        iteration_counter += 1
        results = snapshot.execute_sql(
            "SELECT col1, col2, col3, col4, col5, col6, col7, col8, col9, col10 FROM memory_leak_test limit 250000"
        )

        for row in results:
            if row[0] == "not gonna happen, this is just to reference row":
                pass


def execute_queries(database, executions):
    process = psutil.Process(os.getpid())
    print(f"Starting memory: {(process.memory_info().rss * 0.000001):.2f}mb")

    for i in range(executions):
        print(
            f"Memory after iteration {i+1}: {(process.memory_info().rss * 0.000001):.2f}mb"
        )

        _query_data(database)
        gc.collect()  # just in case, who knows

    print(f"Ending memory: {(process.memory_info().rss * 0.000001):.2f}mb")


def main():
    instance_id = <instance_id>
    database_id = <database_id>
    executions = 30

    spanner_client = spanner.Client()
    instance = spanner_client.instance(instance_id)
    database = instance.database(database_id)

    execute_queries(database, executions)


if __name__ == "__main__":
    main()
```

#### Stack trace / Output
```
Starting memory: 43.42mb
Memory after iteration 1: 43.42mb
Memory after iteration 2: 140.15mb
Memory after iteration 3: 152.90mb
Memory after iteration 4: 161.35mb
Memory after iteration 5: 164.79mb
Memory after iteration 6: 174.70mb
Memory after iteration 7: 182.70mb
Memory after iteration 8: 188.95mb
Memory after iteration 9: 199.01mb
Memory after iteration 10: 199.58mb
Memory after iteration 11: 203.47mb
Memory after iteration 12: 204.28mb
Memory after iteration 13: 204.29mb
Memory after iteration 14: 207.27mb
Memory after iteration 15: 210.12mb
Memory after iteration 16: 213.60mb
Memory after iteration 17: 218.86mb
Memory after iteration 18: 218.91mb
Memory after iteration 19: 221.39mb
Memory after iteration 20: 221.99mb
Memory after iteration 21: 222.38mb
Memory after iteration 22: 222.39mb
Memory after iteration 23: 222.39mb
Memory after iteration 24: 222.74mb
Memory after iteration 25: 222.97mb
Memory after iteration 26: 223.19mb
Memory after iteration 27: 223.54mb
Memory after iteration 28: 223.54mb
Memory after iteration 29: 224.00mb
Memory after iteration 30: 224.02mb
Ending memory: 224.05mb
```

Thanks

**Comment by javilasparta** [comment]
Support case: https://console.cloud.google.com/support/cases/detail/v2/42562731?project=spartandev-156101

**Comment by asthamohta** [comment]
Hi @javilasparta.
I tested the code after adding one million non empty rows into the table as suggested by you and added an extra row to check memory usage here:
`def execute_queries(database, executions):
    process = psutil.Process(os.getpid())
    print(f"Starting memory: {(process.memory_info().rss * 0.000001):.2f}mb")

    for i in range(executions):
        print(
            f"Memory after iteration {i+1}: {(process.memory_info().rss * 0.000001):.2f}mb"
        )

        _query_data(database)
        gc.collect()  # just in case, who knows
        print(
            f"Memory before iteration {i+2}: {(process.memory_info().rss * 0.000001):.2f}mb"
        )

    print(f"Ending memory: {(process.memory_info().rss * 0.000001):.2f}mb")`

My results were as following:
Starting memory: 41.83mb
Memory after iteration 1: 41.84mb
Memory before iteration 2: 120.71mb
Memory after iteration 2: 120.71mb
Memory before iteration 3: 124.50mb
Memory after iteration 3: 124.50mb
Memory before iteration 4: 128.50mb
Memory after iteration 4: 128.50mb
Memory before iteration 5: 130.34mb
Memory after iteration 5: 130.34mb
Memory before iteration 6: 131.48mb
Memory after iteration 6: 131.48mb
Memory before iteration 7: 129.93mb
Memory after iteration 7: 129.93mb
Memory before iteration 8: 129.92mb
Memory after iteration 8: 129.92mb
Memory before iteration 9: 132.29mb
Memory after iteration 9: 132.29mb
Memory before iteration 10: 131.91mb
Memory after iteration 10: 131.91mb
Memory before iteration 11: 126.17mb
Memory after iteration 11: 126.17mb
Memory before iteration 12: 128.69mb
Memory after iteration 12: 128.69mb
Memory before iteration 13: 129.94mb
Memory after iteration 13: 129.94mb
Memory before iteration 14: 130.20mb
Memory after iteration 14: 130.20mb
Memory before iteration 15: 131.23mb
Memory after iteration 15: 131.23mb
Memory before iteration 16: 121.74mb
Memory after iteration 16: 121.74mb
Memory before iteration 17: 118.64mb
Memory after iteration 17: 118.64mb
Memory before iteration 18: 120.20mb
Memory after iteration 18: 120.20mb
Memory before iteration 19: 121.30mb
Memory after iteration 19: 121.30mb
Memory before iteration 20: 126.41mb
Memory after iteration 20: 126.41mb
Memory before iteration 21: 126.75mb
Memory after iteration 21: 126.75mb
Memory before iteration 22: 122.49mb
Memory after iteration 22: 122.49mb
Memory before iteration 23: 126.36mb
Memory after iteration 23: 126.36mb
Memory before iteration 24: 124.81mb
Memory after iteration 24: 124.81mb
Memory before iteration 25: 126.51mb
Memory after iteration 25: 126.51mb
Memory before iteration 26: 124.87mb
Memory after iteration 26: 124.87mb
Memory before iteration 27: 126.67mb
Memory after iteration 27: 126.67mb
Memory before iteration 28: 128.45mb
Memory after iteration 28: 128.45mb
Memory before iteration 29: 123.10mb
Memory after iteration 29: 123.10mb
Memory before iteration 30: 124.19mb
Memory after iteration 30: 124.19mb
Memory before iteration 31: 124.57mb
Ending memory: 124.57mb


Memory before and after each iteration of the _query_data() is similar which leads me to believe there isn't a memory leak.

**Comment by javilasparta** [comment]
@asthamohta the memory leak might not be in _query_data, but I would say there isn't a memory leak, specially if you can see the memory increasing (in your own example), starting from  41.83mb (or 120.71mb in the first iteration) and ending in 124.57mb. Shouldn't the script end again with the same amount of memory it started? (at least 41.83mb).

Now something I notice is the memory increase is way bigger the more rows you need, and it does not go down, even after forcing garbage collecting.

**Comment by asthamohta** [comment]
Hi @javilasparta, I have investigated the code. Can you try this:
After the section where you call Ending memory, add 
```
import time
time.sleep(600)
```
And then check what the memory usage is. For me the memory reduces and goes back down to what is expected.

**Comment by javilasparta** [comment]
Hi @ asthamohta. Sorry for the late response, I was out of the office for a few days, I'll try that and get back to you

**Comment by javilasparta** [comment]
@asthamohta That's odd, it didn't go down for me after 10min (600s):

Note: I set executions = 10 to speed up getting the results.

Starting memory: 44.10mb
Memory after iteration 1: 44.10mb
Memory after iteration 2: 139.30mb
Memory after iteration 3: 174.60mb
Memory after iteration 4: 188.53mb
Memory after iteration 5: 196.29mb
Memory after iteration 6: 200.73mb
Memory after iteration 7: 204.68mb
Memory after iteration 8: 218.64mb
Memory after iteration 9: 221.07mb
Memory after iteration 10: 221.34mb
Ending memory before sleep: 232.56mb
Ending memory after sleep: 232.67mb

I only changed this in the script, as you told me:

```
def execute_queries(database, executions):
...
    print(f"Ending memory before sleep: {(process.memory_info().rss * 0.000001):.2f}mb")

    time.sleep(600)

    print(f"Ending memory after sleep: {(process.memory_info().rss * 0.000001):.2f}mb")
```

**Comment by asthamohta** [comment]
Hi @javilasparta, actually could you try further increasing the time out?
These are my results after timing out for 20 minutes:
```
Starting memory: 81.23mb
Memory after iteration 1: 81.24mb
1
Memory before iteration 2: 136.29mb
Memory after iteration 2: 136.29mb
2
Memory before iteration 3: 141.03mb
Memory after iteration 3: 141.03mb
3
Memory before iteration 4: 139.72mb
Memory after iteration 4: 139.72mb
4
Memory before iteration 5: 141.23mb
Memory after iteration 5: 141.23mb
5
Memory before iteration 6: 142.79mb
Memory after iteration 6: 142.79mb
6
Memory before iteration 7: 141.48mb
Memory after iteration 7: 141.48mb
7
Memory before iteration 8: 143.93mb
Memory after iteration 8: 143.93mb
8
Memory before iteration 9: 142.96mb
Memory after iteration 9: 142.96mb
9
Memory before iteration 10: 141.57mb
Memory after iteration 10: 141.57mb
10
Memory before iteration 11: 144.31mb
Ending memory: 144.31mb
Application memory before timeout: 144.31mb
Application memory after timeout: 90.53mb
```

My suspicion is that the increase in memory is due to the sessions which are checked out of the pool and after they are returned to the pool it takes some time for their memory to be released. Along with this in a code as yours, I would suggest using a single snapshot which is multi_use for faster results as following:
```
def _query_data(snapshot):
    """Queries sample data from the database using SQL."""

    with snapshot as snapshot:
        results=snapshot.execute_sql(
            "SELECT col1, col2, col3, col4, col5, col6, col7, col8, col9, col10 FROM memory_leak_test limit 250000"
        )

        for row in results:
            if row[0] == "not gonna happen, this is just to reference row":
                pass

def execute_queries(database, executions):
    process = psutil.Process(os.getpid())
    print(f"Starting memory: {(process.memory_info().rss * 0.000001):.2f}mb")
    snapshot = database.snapshot(multi_use = True)
    for i in range(executions):
        print(
            f"Memory after iteration {i+1}: {(process.memory_info().rss * 0.000001):.2f}mb"
        )
        print(i+1)

        _query_data(snapshot)
        gc.collect()
        # just in case, who knows
        print(
            f"Memory before iteration {i+2}: {(process.memory_info().rss * 0.000001):.2f}mb"
        )

    print(f"Ending memory: {(process.memory_info().rss * 0.000001):.2f}mb")
```

**Comment by javilasparta** [comment]
Thank asthamohta

I tried with 20min but got the same results (no memory released). I will, however, try also adding the multi_use flag and get back to you.

**Comment by asthamohta** [comment]
Thanks @javilasparta, please let me know if that helps

**Comment by javilasparta** [comment]
@asthamohta I tried your recommendations, but they didn't work. I even tried with 30min sleep and using the multi-use=true

Starting memory: 43.86mb
Memory after iteration 1: 43.86mb
Memory after iteration 2: 140.58mb
Memory after iteration 3: 165.25mb
Memory after iteration 4: 176.68mb
Memory after iteration 5: 185.84mb
Memory after iteration 6: 189.78mb
Memory after iteration 7: 194.49mb
Memory after iteration 8: 199.30mb
Memory after iteration 9: 202.57mb
Memory after iteration 10: 208.75mb
Ending memory before sleep: 210.87mb
Ending memory after sleep: 210.98mb

**Comment by javilasparta** [comment]
I did a pip freeze, just to verify we are working with the same versions:

build==0.9.0
cachetools==5.2.0
certifi==2022.9.24
charset-normalizer==2.1.1
click==8.1.3
google-api-core==2.11.0
google-auth==2.15.0
google-cloud-core==2.3.2
google-cloud-spanner==3.24.0
googleapis-common-protos==1.57.0
grpc-google-iam-v1==0.12.4
grpcio==1.51.1
grpcio-status==1.51.1
idna==3.4
packaging==21.3
pep517==0.13.0
pip-tools==6.11.0
proto-plus==1.22.1
protobuf==4.21.10
psutil==5.9.4
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==3.0.9
requests==2.28.1
rsa==4.9
six==1.16.0
sqlparse==0.4.3
tomli==2.0.1
urllib3==1.26.1

**Comment by asthamohta** [comment]
Thanks @javilasparta , we're trying to recreate the issue. It seems the memory is proportional to the number of rows so we'll try it with a larger database once

**Comment by asthamohta** [comment]
Hey @javilasparta, we are having a hard time identifying the source of the memory leak and wanted to ask what impact this was having on you and if anything helps decrease the memory

**Comment by javilasparta** [comment]
Hi @asthamohta, I understand. Currently, we have a containerized python application running in k8s. The pod memory is limited, when this limit is reached k8s restarts the pod. After debugging we noticed the memory kept going up as time passed by, therefore we have to deal with pods often restarting as the memory is released.

We found out this memory increase pattern, and that it had to do with the spanner library, which is why we created this isolated script based only on examples from the spanner python client documentation to double-check and verify that the memory was not released (and confirmed as well when making adjustments to wait for 30mins, etc). 

So far since the memory is not released as I have seen when running this isolated script, we have not taken any particular action as the problem comes (from my understanding) from the library. We continue experiencing pod restarts.

Were you able to replicate the problem (memory not being released) with the dependency version I shared?

**Comment by asthamohta** [comment]
Hey @javilasparta, still the same resume. I used the 3.9 version of python and 3.24 version of python spanner and for me the memory went down, so not been able to find the leak:

(mem) asthamohta-macbookpro1:Documents asthamohta$ python3 memory-leak.py
Starting memory: 50.70mb
Memory after iteration 1: 50.71mb
1
Memory before iteration 2: 82.92mb
Memory after iteration 2: 82.92mb
2
Memory before iteration 3: 87.15mb
Memory after iteration 3: 87.15mb
3
Memory before iteration 4: 90.51mb
Memory after iteration 4: 90.51mb
4
Memory before iteration 5: 90.80mb
Memory after iteration 5: 90.80mb
5
Memory before iteration 6: 87.77mb
Memory after iteration 6: 87.77mb
6
Memory before iteration 7: 86.93mb
Memory after iteration 7: 86.93mb
7
Memory before iteration 8: 87.71mb
Memory after iteration 8: 87.71mb
8
Memory before iteration 9: 91.14mb
Memory after iteration 9: 91.14mb
9
Memory before iteration 10: 90.87mb
Memory after iteration 10: 90.87mb
10
Memory before iteration 11: 87.61mb
Ending memory: 87.61mb
7: 87.61mb
8: 11.02mb
(mem) asthamohta-macbookpro1:Documents asthamohta$ pip freeze
cachetools==5.3.0
certifi==2022.12.7
charset-normalizer==3.0.1
google-api-core==2.11.0
google-auth==2.16.0
google-cloud-core==2.3.2
google-cloud-spanner==3.24.0
googleapis-common-protos==1.58.0
grpc-google-iam-v1==0.12.6
grpcio==1.51.1
grpcio-status==1.51.1
idna==3.4
packaging==23.0
proto-plus==1.22.2
protobuf==4.21.12
psutil==5.9.4
pyasn1==0.4.8
pyasn1-modules==0.2.8
requests==2.28.2
rsa==4.9
six==1.16.0
sqlparse==0.4.3
urllib3==1.26.14

**Comment by asthamohta** [comment]
Would it be possible for you to try this in a virtual environment?

**Comment by javilasparta** [comment]
I will do that (although I do run in it in a venv). Meanwhile, in the output you shared the initial memory was:

Starting memory: 50.70mb
but
Ending memory: 87.61mb

So it didn't go down in tour own output? or I'm not sure if I missed something from your output.

**Comment by asthamohta** [comment]
The memory before sleep is that. After sleep is 11.02mb.

**Comment by asthamohta** [comment]
Hi @javilasparta, closing this as no new response received from you. Feel free to open this if needed.
