### ISSUE TITLE
Is there an option to return execute_sql results as a list of dictionaries?

### ISSUE THREAD

**Issue by yaozhang09** [googleapis/python-spanner#958]
right now the results returned from `snapshot.execute_sql()` gets returned as a list of arrays.  Is there an existing configuration to change the return format of the StreamedResultSet object?

I would like to use keys instead of row indices when pulling values out for further processing. If i ever had to update the running query I would have to make sure my indices are correct. I can easily convert the row to dictionary but want to see if there's a configuration i'm missing.

**Comment by asthamohta** [comment]
hi @yaozhang09, currently we don't. If you like we can add an additional function which you can use on the result returned. But we won't be able to change the existing functionality as it will be breaking change. Let me know 😊

**Comment by asthamohta** [comment]
Sure give me some time. Thanks

**Comment by asthamohta** [comment]
Hi @yaozhang09, can you check if this is as requested? https://github.com/googleapis/python-spanner/pull/1003/files

**Comment by yaozhang09** [comment]
sorry just following up, this LGTM
