### ISSUE TITLE
ALTER INDEX DDL statement cannot be parsed

### ISSUE THREAD

**Issue by shay93** [googleapis/python-spanner#960]
#### Environment details

  - OS type and version: Mac OS Ventura 13.2.1
  - Python version: 3.9.6
  - pip version: pip 21.2.4
  - `google-cloud-spanner` version: Version: 3.36.0

#### Steps to reproduce

  1. Execute an ALTER INDEX statement. The one I tried was ALTER INDEX <index_name> ADD STORED COLUMN <column_name>.
  2. Expect that the statement will succeed instead receive the following error:
  
  grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Error parsing Spanner DDL statement: ALTER INDEX <index_name> ADD STORED COLUMN <column_name> : Syntax error on line 1, column 7: Encountered 'INDEX' while parsing: alter_statement"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2023-06-20T17:35:39.630488-04:00", grpc_status:3, grpc_message:"Error parsing Spanner DDL statement: ALTER INDEX sampling_request_by_shard_channel_creation_time_desc ADD STORED COLUMN user_id : Syntax error on line 1, column 7: Encountered \'INDEX\' while parsing: alter_statement"}"
>

#### Code example

```python
database.update_ddl(['ALTER INDEX <index_name> ADD STORED COLUMN <column_name>'])
```

#### Stack trace
```
  grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Error parsing Spanner DDL statement: ALTER INDEX <index_name> ADD STORED COLUMN <column_name> : Syntax error on line 1, column 7: Encountered 'INDEX' while parsing: alter_statement"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2023-06-20T17:35:39.630488-04:00", grpc_status:3, grpc_message:"Error parsing Spanner DDL statement: ALTER INDEX sampling_request_by_shard_channel_creation_time_desc ADD STORED COLUMN user_id : Syntax error on line 1, column 7: Encountered \'INDEX\' while parsing: alter_statement"}"
>

```

**Comment by shay93** [comment]
Hey @asthamohta this is for a Google Sql database. I'll try with the syntax above and see if it works though. thanks!

**Comment by asthamohta** [comment]
Hey @shay93, closing this as no new response received from you. Feel free to open this if needed.
